exports.MAIN = {
	/* --------------------------- Server --------------------------- */
	SERVER_ID: null, // Server identifier (e.g., 'hp-terminal', 'pl-cluster', 'de1'). Use 'development' for testing only. 'production' has no effect. Use null to leave it unset.
	EXTENDED_LOGS: false, // Specifies whether the script should display additional information in the logs.
	UFW_LOG_FILE: '/var/log/ufw.log',
	CACHE_FILE: '/var/cache/sefinek/ufw-spamverify-reporter.cache',

	/* --------------------------- Network --------------------------- */
	IP_ASSIGNMENT: 'dynamic', // IP assignment type: 'static' for a fixed IP, 'dynamic' if it may change over time.
	IP_REFRESH_SCHEDULE: '0 */6 * * *', // Cron schedule for checking the public IP assigned by your ISP. Used only with dynamic IPs to prevent accidental self-reporting. If IP_ASSIGNMENT is set to 'static', the script will check your IP only once.
	IPv6_SUPPORT: true, // IPv6 support: true if the device has a globally routable address assigned by the ISP.

	/* --------------------------- Reports --------------------------- */
	SPAMVERIFY_API_KEY: '',
	IP_REPORT_COOLDOWN: 12 * 60 * 60 * 1000, // Minimum time between reports of the same IP. Must be >= 15 minutes. Do not set values like 1 hour, as it wouldn't make sense due to rate limits.

	/* --------------------------- Automatic Updates --------------------------- */
	AUTO_UPDATE_ENABLED: false, // Automatic updates: true to enable auto-update via 'git pull', false to disable.
	AUTO_UPDATE_SCHEDULE: '0 15,17,18,20 * * *', // Cron schedule for automatic script updates. Default: every day at 15:00, 17:00, 18:00, 20:00

	/* --------------------------- Discord Webhooks --------------------------- */
	DISCORD_WEBHOOK_ENABLED: false, // Enables sending Discord webhooks with error reports, execution status, and other events.
	DISCORD_WEBHOOK_URL: '',
	DISCORD_WEBHOOK_USERNAME: 'SERVER_ID', // Username shown as the message author. Use null for default. 'SERVER_ID' will resolve to this.MAIN.SERVER_ID.
};


// Generates a report submission.
const serverId = this.MAIN.SERVER_ID ? `on ${this.MAIN.SERVER_ID} ` : '';
exports.REPORT_COMMENT = ({ date, srcIp, dstIp, proto, spt, dpt, In, Out, mac, len, ttl, id, tos, prec, res, window, urgp, syn }, fullLog) =>
	`Blocked by UFW ${serverId}[${dpt}/${proto?.toLowerCase()}]. Generated by: https://github.com/sefinek/UFW-SpamVerify-Reporter`; // Please don't delete this URL, I'd be very grateful. Thank you! 💙


// See: https://spamverify.readme.io/reference/categories
const categories = {
	22: '8,14,10,18', // SSH: Port Scan, SSH, Brute Force, Phishing
	23: '8,15,10,18', // Telnet: Port Scan, IoT Targeted, Brute Force, Phishing
	21: '8,16,18', // FTP: Port Scan, FTP Brute Force, Phishing
	53: '8,1,2', // DNS: Port Scan, DNS Compromise, DNS Poisoning
	80: '8,13', // HTTP: Port Scan, Web App Attack
	443: '8,13', // HTTPS: Port Scan, Web App Attack
};

exports.DETERMINE_CATEGORIES = ({ dpt }) => categories[dpt] || '8'; // Default: Port Scan